spring.application.name=fly-and-seek-auth
spring.data.mongodb.uri=mongodb://localhost:27017/flyandseek

# Optional: Disable verbose logging for JWT or security if needed
logging.level.org.springframework.security=INFO
